services:
  app:
    image: mcr.microsoft.com/devcontainers/php:1-8.3-bookworm
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
    network_mode: service:db
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: kere
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: kere
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
